image: Visual Studio 2015
environment:
  BOOST_ROOT: C:\Libraries\boost_1_66_0
  # If the Gradle Daemon is used, AppVeyor waits forever for it to terminate
  GRADLE_OPTS: -Dorg.gradle.daemon=false
init:
  # Print Remote Desktop information for debugging porposes
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build_script:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 14 2015"
  - cmake --build . --config Release --target package
  - cd %APPVEYOR_BUILD_FOLDER%
test_script:
  - build\rhubarb\Release\runTests.exe
artifacts:
  - path: build\rhubarb-lip-sync-*.zip
